# -*- coding: utf-8 -*-
"""filterdistancedataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O49M1tH3Z3lNRI8DBA8DWzPDvmxgiHVj
"""

import pandas as pd

df=pd.read_csv("fullDataSimian.csv")
df

# Show rows where Column1 and Column2 have the same values
result = df[df['cluster_1'] == df['cluster_2']]
del result['RowNumber']
del result['NewSortColumn']
result

result.to_csv("filteredDistances.csv",index=None)

